"""baseline schema

Revision ID: 07c4ee33b7fa
Revises: 
Create Date: 2026-06-11 17:44:46.255335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c4ee33b7fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('bill_to_block', sa.Text(), nullable=False),
    sa.Column('description_headline', sa.String(length=256), nullable=False),
    sa.Column('description_subtitle', sa.Text(), nullable=True),
    sa.Column('period_label', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('brand_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_brand_code'), ['brand_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_number'), ['number'], unique=True)

    op.create_table('sample_allowances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('allowance_units', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'year', 'month', name='uq_allowance_brand_period')
    )
    with op.batch_alter_table('sample_allowances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_allowances_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_allowances_year'), ['year'], unique=False)

    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shops_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_shops_slug'), ['slug'], unique=True)

    op.create_table('ad_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_ad_credits_year_month')
    )
    with op.batch_alter_table('ad_credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_credits_applied_date'), ['applied_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_credits_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_credits_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_credits_year'), ['year'], unique=False)

    op.create_table('bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('bundle_sku', sa.String(length=128), nullable=True),
    sa.Column('tiktok_sku_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('variation', sa.String(length=256), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.String(length=16), nullable=False),
    sa.Column('msrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bundles_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_bundles_bundle_sku'), ['bundle_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_bundles_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bundles_tiktok_sku_id'), ['tiktok_sku_id'], unique=False)

    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('handle', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'handle', 'platform', name='uq_creator_per_shop_platform')
    )
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creators_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_creators_handle'), ['handle'], unique=False)
        batch_op.create_index(batch_op.f('ix_creators_shop_id'), ['shop_id'], unique=False)

    op.create_table('gmv_max_campaign_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sku_orders', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_gmv_max_campaign_metrics_year_month')
    )
    with op.batch_alter_table('gmv_max_campaign_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmv_max_campaign_metrics_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmv_max_campaign_metrics_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmv_max_campaign_metrics_year'), ['year'], unique=False)

    op.create_table('gmv_max_reimbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_gmv_max_reimbursements_year_month')
    )
    with op.batch_alter_table('gmv_max_reimbursements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmv_max_reimbursements_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmv_max_reimbursements_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmv_max_reimbursements_year'), ['year'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('TIKTOK_ORDERS', 'TIKTOK_SETTLEMENTS', 'TIKTOK_PAYOUTS', 'TIKTOK_ADS', 'TIKTOK_ANALYTICS', 'TIKTOK_GMV_MAX', 'SKU_MASTER', 'BUNDLE_MAPPING', 'SAMPLES', 'INVENTORY_SNAPSHOT', 'SUPPLIER_RECEIPTS', name='importfilekind'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='importbatchstatus'), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_status'), ['status'], unique=False)

    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoices_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_shop_id'), ['shop_id'], unique=False)

    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('tiktok_alt_sku', sa.String(length=128), nullable=True),
    sa.Column('tiktok_sku_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('item_type', sa.String(length=64), nullable=True),
    sa.Column('msrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cogs', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('moq', sa.Integer(), nullable=True),
    sa.Column('case_pack', sa.Integer(), nullable=True),
    sa.Column('safety_stock_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_reorderable', sa.Boolean(), nullable=False),
    sa.Column('service_level', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skus_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_skus_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skus_sku'), ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_skus_tiktok_alt_sku'), ['tiktok_alt_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_skus_tiktok_sku_id'), ['tiktok_sku_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_super_admin'), ['is_super_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_shop_id'), ['shop_id'], unique=False)

    op.create_table('ad_spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('spend_date', sa.DateTime(), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_name', sa.String(length=512), nullable=True),
    sa.Column('cash_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ad_credit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('campaign_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spend_date', 'campaign_id', name='uq_ad_spend_date_campaign')
    )
    with op.batch_alter_table('ad_spend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_spend_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_spend_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_spend_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_spend_spend_date'), ['spend_date'], unique=False)

    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('adjustment_id', sa.String(length=64), nullable=False),
    sa.Column('adjustment_type', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('settlement_time', sa.DateTime(), nullable=True),
    sa.Column('linked_statement_id', sa.String(length=64), nullable=True),
    sa.Column('linked_payout_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adjustment_id', 'adjustment_type', 'create_time', name='uq_adjustment_natural_key')
    )
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adjustments_adjustment_id'), ['adjustment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustments_adjustment_type'), ['adjustment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustments_create_time'), ['create_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustments_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustments_linked_payout_id'), ['linked_payout_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustments_linked_statement_id'), ['linked_statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustments_settlement_time'), ['settlement_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustments_shop_id'), ['shop_id'], unique=False)

    op.create_table('bundle_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('component_sku', sa.String(length=128), nullable=False),
    sa.Column('component_name', sa.String(length=512), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('msrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cogs', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bundle_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bundle_components_bundle_id'), ['bundle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bundle_components_component_sku'), ['component_sku'], unique=False)

    op.create_table('gmv_max_daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sku_orders', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', name='uq_gmv_max_daily_date')
    )
    with op.batch_alter_table('gmv_max_daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmv_max_daily_metrics_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmv_max_daily_metrics_metric_date'), ['metric_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmv_max_daily_metrics_shop_id'), ['shop_id'], unique=False)

    op.create_table('inventory_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', 'captured_at', name='uq_inventory_sku_captured_at')
    )
    with op.batch_alter_table('inventory_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_snapshots_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_snapshots_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_snapshots_sku'), ['sku'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('tiktok_order_id', sa.String(length=64), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('order_type', sa.Enum('PAID', 'SAMPLE', 'PAID_SAMPLE', name='ordertype'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('refunds', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_fees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_referral_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_transaction_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_refund_admin_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_sales_tax_on_referral', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_smart_promo_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_campaign_fees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_partner_commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_managed_service', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('affiliate_commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shop_ads_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('seller_funded_discount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('seller_funded_outlandish', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('seller_funded_smashbox', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_platform_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_policy_violation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_discount_policy_violation'), ['discount_policy_violation'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_type'), ['order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_placed_at'), ['placed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tiktok_order_id'), ['tiktok_order_id'], unique=True)

    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('payout_id', sa.String(length=64), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_payout_id'), ['payout_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payouts_shop_id'), ['shop_id'], unique=False)

    op.create_table('purchase_invoice_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=False),
    sa.Column('credit_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_invoice_credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoice_credits_purchase_invoice_id'), ['purchase_invoice_id'], unique=False)

    op.create_table('purchase_invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_invoice_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoice_payments_purchase_invoice_id'), ['purchase_invoice_id'], unique=False)

    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('creator_handle', sa.String(length=256), nullable=True),
    sa.Column('is_paid_oversample', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_samples_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_is_paid_oversample'), ['is_paid_oversample'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_shipped_at'), ['shipped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_sku'), ['sku'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('tiktok_order_id', sa.String(length=64), nullable=False),
    sa.Column('linked_statement_id', sa.String(length=64), nullable=True),
    sa.Column('linked_payout_id', sa.String(length=64), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('settled_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.String(length=64), nullable=True),
    sa.Column('sample_order_type', sa.String(length=128), nullable=True),
    sa.Column('order_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_order_margin', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_sales_refund', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('seller_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('seller_discount_refund', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_fees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_referral_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_transaction_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_refund_admin_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_sales_tax_on_referral', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_smart_promo_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_campaign_fees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_partner_commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tiktok_managed_service', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('affiliate_commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shop_ads_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tiktok_order_id', 'linked_statement_id', name='uq_settlement_order_statement'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_linked_payout_id'), ['linked_payout_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_linked_statement_id'), ['linked_statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_paid_date'), ['paid_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_sample_order_type'), ['sample_order_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_settled_date'), ['settled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlements_tiktok_order_id'), ['tiktok_order_id'], unique=False)

    op.create_table('sku_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('alias_sku', sa.String(length=128), nullable=False),
    sa.Column('canonical_sku', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'alias_sku', name='uq_sku_alias_per_shop')
    )
    with op.batch_alter_table('sku_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_aliases_alias_sku'), ['alias_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_aliases_canonical_sku'), ['canonical_sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_aliases_shop_id'), ['shop_id'], unique=False)

    op.create_table('tiktok_daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('gmv', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('customers', sa.Integer(), nullable=False),
    sa.Column('items_sold', sa.Integer(), nullable=False),
    sa.Column('items_canceled_returned', sa.Integer(), nullable=False),
    sa.Column('items_refunded', sa.Integer(), nullable=False),
    sa.Column('aov', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gmv_with_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shipping_fees', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', name='uq_tt_daily_date')
    )
    with op.batch_alter_table('tiktok_daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tiktok_daily_metrics_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tiktok_daily_metrics_metric_date'), ['metric_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tiktok_daily_metrics_shop_id'), ['shop_id'], unique=False)

    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('platform_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('post_tiktok_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('seller_funded_discount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('seller_funded_outlandish', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('seller_funded_smashbox', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_policy_violation', sa.Boolean(), nullable=False),
    sa.Column('policy_violation_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('policy_violation_acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('unit_cogs_snapshot', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_lines_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_lines_policy_violation_acknowledged'), ['policy_violation_acknowledged'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_lines_sku'), ['sku'], unique=False)

    op.create_table('sample_inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', name='samplemovementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('moved_at', sa.DateTime(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sample_inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sample_inventory_movements_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_inventory_movements_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_inventory_movements_moved_at'), ['moved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_inventory_movements_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_inventory_movements_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sample_inventory_movements_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_inventory_movements_sku'))
        batch_op.drop_index(batch_op.f('ix_sample_inventory_movements_shop_id'))
        batch_op.drop_index(batch_op.f('ix_sample_inventory_movements_sample_id'))
        batch_op.drop_index(batch_op.f('ix_sample_inventory_movements_moved_at'))
        batch_op.drop_index(batch_op.f('ix_sample_inventory_movements_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_sample_inventory_movements_brand'))

    op.drop_table('sample_inventory_movements')
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_lines_sku'))
        batch_op.drop_index(batch_op.f('ix_order_lines_policy_violation_acknowledged'))
        batch_op.drop_index(batch_op.f('ix_order_lines_order_id'))

    op.drop_table('order_lines')
    with op.batch_alter_table('tiktok_daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tiktok_daily_metrics_shop_id'))
        batch_op.drop_index(batch_op.f('ix_tiktok_daily_metrics_metric_date'))
        batch_op.drop_index(batch_op.f('ix_tiktok_daily_metrics_import_batch_id'))

    op.drop_table('tiktok_daily_metrics')
    with op.batch_alter_table('sku_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_aliases_shop_id'))
        batch_op.drop_index(batch_op.f('ix_sku_aliases_canonical_sku'))
        batch_op.drop_index(batch_op.f('ix_sku_aliases_alias_sku'))

    op.drop_table('sku_aliases')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_tiktok_order_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_shop_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_settled_date'))
        batch_op.drop_index(batch_op.f('ix_settlements_sample_order_type'))
        batch_op.drop_index(batch_op.f('ix_settlements_paid_date'))
        batch_op.drop_index(batch_op.f('ix_settlements_linked_statement_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_linked_payout_id'))
        batch_op.drop_index(batch_op.f('ix_settlements_import_batch_id'))

    op.drop_table('settlements')
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_samples_sku'))
        batch_op.drop_index(batch_op.f('ix_samples_shop_id'))
        batch_op.drop_index(batch_op.f('ix_samples_shipped_at'))
        batch_op.drop_index(batch_op.f('ix_samples_is_paid_oversample'))
        batch_op.drop_index(batch_op.f('ix_samples_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_samples_creator_id'))

    op.drop_table('samples')
    with op.batch_alter_table('purchase_invoice_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_payments_purchase_invoice_id'))

    op.drop_table('purchase_invoice_payments')
    with op.batch_alter_table('purchase_invoice_credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoice_credits_purchase_invoice_id'))

    op.drop_table('purchase_invoice_credits')
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_shop_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_payout_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_paid_at'))
        batch_op.drop_index(batch_op.f('ix_payouts_import_batch_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_tiktok_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_shop_id'))
        batch_op.drop_index(batch_op.f('ix_orders_placed_at'))
        batch_op.drop_index(batch_op.f('ix_orders_order_type'))
        batch_op.drop_index(batch_op.f('ix_orders_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_orders_discount_policy_violation'))
        batch_op.drop_index(batch_op.f('ix_orders_brand'))

    op.drop_table('orders')
    with op.batch_alter_table('inventory_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_snapshots_sku'))
        batch_op.drop_index(batch_op.f('ix_inventory_snapshots_shop_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_snapshots_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_snapshots_captured_at'))

    op.drop_table('inventory_snapshots')
    with op.batch_alter_table('gmv_max_daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmv_max_daily_metrics_shop_id'))
        batch_op.drop_index(batch_op.f('ix_gmv_max_daily_metrics_metric_date'))
        batch_op.drop_index(batch_op.f('ix_gmv_max_daily_metrics_import_batch_id'))

    op.drop_table('gmv_max_daily_metrics')
    with op.batch_alter_table('bundle_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bundle_components_component_sku'))
        batch_op.drop_index(batch_op.f('ix_bundle_components_bundle_id'))

    op.drop_table('bundle_components')
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adjustments_shop_id'))
        batch_op.drop_index(batch_op.f('ix_adjustments_settlement_time'))
        batch_op.drop_index(batch_op.f('ix_adjustments_linked_statement_id'))
        batch_op.drop_index(batch_op.f('ix_adjustments_linked_payout_id'))
        batch_op.drop_index(batch_op.f('ix_adjustments_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_adjustments_create_time'))
        batch_op.drop_index(batch_op.f('ix_adjustments_adjustment_type'))
        batch_op.drop_index(batch_op.f('ix_adjustments_adjustment_id'))

    op.drop_table('adjustments')
    with op.batch_alter_table('ad_spend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_spend_spend_date'))
        batch_op.drop_index(batch_op.f('ix_ad_spend_shop_id'))
        batch_op.drop_index(batch_op.f('ix_ad_spend_import_batch_id'))
        batch_op.drop_index(batch_op.f('ix_ad_spend_campaign_id'))

    op.drop_table('ad_spend')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_shop_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_super_admin'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skus_tiktok_sku_id'))
        batch_op.drop_index(batch_op.f('ix_skus_tiktok_alt_sku'))
        batch_op.drop_index(batch_op.f('ix_skus_sku'))
        batch_op.drop_index(batch_op.f('ix_skus_shop_id'))
        batch_op.drop_index(batch_op.f('ix_skus_brand'))

    op.drop_table('skus')
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_shop_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_number'))

    op.drop_table('purchase_invoices')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_status'))
        batch_op.drop_index(batch_op.f('ix_import_batches_shop_id'))
        batch_op.drop_index(batch_op.f('ix_import_batches_kind'))

    op.drop_table('import_batches')
    with op.batch_alter_table('gmv_max_reimbursements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmv_max_reimbursements_year'))
        batch_op.drop_index(batch_op.f('ix_gmv_max_reimbursements_shop_id'))
        batch_op.drop_index(batch_op.f('ix_gmv_max_reimbursements_month'))

    op.drop_table('gmv_max_reimbursements')
    with op.batch_alter_table('gmv_max_campaign_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmv_max_campaign_metrics_year'))
        batch_op.drop_index(batch_op.f('ix_gmv_max_campaign_metrics_shop_id'))
        batch_op.drop_index(batch_op.f('ix_gmv_max_campaign_metrics_month'))

    op.drop_table('gmv_max_campaign_metrics')
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creators_shop_id'))
        batch_op.drop_index(batch_op.f('ix_creators_handle'))
        batch_op.drop_index(batch_op.f('ix_creators_brand'))

    op.drop_table('creators')
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bundles_tiktok_sku_id'))
        batch_op.drop_index(batch_op.f('ix_bundles_shop_id'))
        batch_op.drop_index(batch_op.f('ix_bundles_bundle_sku'))
        batch_op.drop_index(batch_op.f('ix_bundles_brand'))

    op.drop_table('bundles')
    with op.batch_alter_table('ad_credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_credits_year'))
        batch_op.drop_index(batch_op.f('ix_ad_credits_shop_id'))
        batch_op.drop_index(batch_op.f('ix_ad_credits_month'))
        batch_op.drop_index(batch_op.f('ix_ad_credits_applied_date'))

    op.drop_table('ad_credits')
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_slug'))
        batch_op.drop_index(batch_op.f('ix_shops_is_active'))

    op.drop_table('shops')
    with op.batch_alter_table('sample_allowances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sample_allowances_year'))
        batch_op.drop_index(batch_op.f('ix_sample_allowances_brand'))

    op.drop_table('sample_allowances')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_brand_code'))

    op.drop_table('invoices')
    # ### end Alembic commands ###
